### ISSUE TITLE
How to loop through every line of a file?

### ISSUE THREAD

**Issue by issachan** [dangelov/hasher#17]
I have 100K lines in my file and I would like them hashed individually. Is there a way to do that with your script?

Thanks

**Comment by dangelov** [comment]
Hey,

Yeah, that's kind of possible, if you make separate selections for each line of your file - though that might be a bit tricky/time consuming with 100k lines.

On a Mac, I'd just hold Option while left-clicking at the very left of the lines, then Cmd+Right arrow to select the whole line. That makes N different selections and hasher will hash each separately.

**Comment by issachan** [comment]
I tried that and it was stopping after one. That's what was weird. I'll try it again though. Thank you

**Comment by issachan** [comment]
Thanks. This worked

**Comment by issachan** [comment]
Thanks. This worked

**Comment by dangelov** [comment]
No problem, great to hear!
